import { THEME_LIGHT_GRAY } from "5-app/settings";

const codeLanguages = [
    "abap",
    "actionscript",
    "ada",
    "cs",
    "cpp",
    "coffeescript",
    "csharp",
    "css",
    "cuda",
    "dart",
    "delphi",
    "elixir",
    "elm",
    "erlang",
    "fortran",
    "foxpro",
    "fsharp",
    "go",
    "graphql",
    "groovy",
    "haskell",
    "html",
    "java",
    "javascript",
    "json",
    "julia",
    "jsx",
    "js",
    "kotlin",
    "latex",
    "lisp",
    "livescript",
    "lua",
    "mathematica",
    "makefile",
    "matlab",
    "objectivec",
    "objective",
    "objectpascal",
    "ocaml",
    "octave",
    "perl",
    "php",
    "powershell",
    "prolog",
    "puppet",
    "python",
    "qml",
    "racket",
    "restructuredtext",
    "rest",
    "ruby",
    "rust",
    "sass",
    "less",
    "scala",
    "scheme",
    "shell",
    "smalltalk",
    "sql",
    "standardml",
    "sml",
    "swift",
    "tcl",
    "tex",
    "text",
    "tsx",
    "typescript",
    "vala",
    "vbnet",
    "verilog",
    "vhdl",
    "xml",
    "xquery",
    "yaml",
];

const codeCustomThemeLight = {
    lineNumberColor: "#383a42",
    lineNumberBgColor: THEME_LIGHT_GRAY,
    backgroundColor: THEME_LIGHT_GRAY,
    textColor: "#383a42",
    substringColor: "#e45649",
    keywordColor: "#a626a4",
    attributeColor: "#50a14f",
    selectorAttributeColor: "#e45649",
    docTagColor: "#a626a4",
    nameColor: "#e45649",
    builtInColor: "#c18401",
    literalColor: "#0184bb",
    bulletColor: "#4078f2",
    codeColor: "#383a42",
    additionColor: "#50a14f",
    regexpColor: "#50a14f",
    symbolColor: "#4078f2",
    variableColor: "#986801",
    templateVariableColor: "#986801",
    linkColor: "#4078f2",
    selectorClassColor: "#986801",
    typeColor: "#986801",
    stringColor: "#50a14f",
    selectorIdColor: "#4078f2",
    quoteColor: "#a0a1a7",
    templateTagColor: "#383a42",
    deletionColor: "#e45649",
    titleColor: "#4078f2",
    sectionColor: "#e45649",
    commentColor: "#a0a1a7",
    metaKeywordColor: "#383a42",
    metaColor: "#4078f2",
    functionColor: "#0834ed",
    numberColor: "#986801",
};
const codeCustomThemeDark = {
    lineNumberColor: "#abb2bf",
    lineNumberBgColor: "#282c34",
    backgroundColor: "#282c34",
    textColor: "#abb2bf",
    substringColor: "#e06c75",
    keywordColor: "#c678dd",
    attributeColor: "#98c379",
    selectorAttributeColor: "#e06c75",
    docTagColor: "#c678dd",
    nameColor: "#e06c75",
    builtInColor: "#e6c07b",
    literalColor: "#56b6c2",
    bulletColor: "#61aeee",
    codeColor: "#abb2bf",
    additionColor: "#98c379",
    regexpColor: "#98c379",
    symbolColor: "#61aeee",
    variableColor: "#d19a66",
    templateVariableColor: "#d19a66",
    linkColor: "#61aeee",
    selectorClassColor: "#d19a66",
    typeColor: "#d19a66",
    stringColor: "#98c379",
    selectorIdColor: "#61aeee",
    quoteColor: "#5c6370",
    templateTagColor: "#abb2bf",
    deletionColor: "#e06c75",
    titleColor: "#61aeee",
    sectionColor: "#e06c75",
    commentColor: "#5c6370",
    metaKeywordColor: "#abb2bf",
    metaColor: "#61aeee",
    functionColor: "#C5BC6D",
    numberColor: "#d19a66",
};

export { codeLanguages, codeCustomThemeLight, codeCustomThemeDark };
